inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
# ~~~ Naming ~~~
# Utilisation d'Unicode dans les noms de méthode
Naming/AsciiIdentifiers:
  Enabled: false
Naming/MethodName:
  Enabled: false
